version: '3.4'

services:
  starter.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=8080
      # - ASPNETCORE_HTTPS_PORTS=8081
    
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  
  starter.blazor:
    environment:
      - apiURL=http://localhost:10001

  starter.vue:
    environment:
      - NODE_ENV=docker
  
  starter.angular:
    environment:
      - NODE_ENV=docker